default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketplace_api_development
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  
test:
  <<: *default
  database: marketplace_api_test
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  
production:
  <<: *default
  database: marketplace_api_production
  username: postgres
  password: <%= ENV["MARKETPLACE_API_DATABASE_PASSWORD"] %>
